name: Autograding All Code

on:
  push:
    paths:
      # Lab 1 files
      - "Lab1/src/main/java/lab1/Division.java"
      - "Lab1/src/test/java/lab1/DivisionTest.java"
      - "Lab1/src/main/java/lab1/Caffeine.java"
      - "Lab1/src/test/java/lab1/CaffeineTest.java"
      - "Lab1/src/main/java/lab1/Mortgage.java"
      - "Lab1/src/test/java/lab1/MortgageTest.java"
      - "Lab1/src/main/java/lab1/NumSquared.java"
      - "Lab1/src/test/java/lab1/NumSquaredTest.java"
      - "Lab1/src/main/java/lab1/OutputWithVars.java"
      - "Lab1/src/test/java/lab1/OutputWithVarsTest.java"
      - "Lab1/src/main/java/lab1/Parking.java"
      - "Lab1/src/test/java/lab1/ParkingTest.java"
      - "Lab1/src/main/java/lab1/BasicOutput.java"
      - "Lab1/src/test/java/lab1/BasicOutputTest.java"

jobs:
  autograding:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean compile

      - name: Run tests
        run: |
          # Handle case where there's no HEAD~1
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "No previous commits. Running all tests."
            mvn test
          else
            if git diff --name-only HEAD~1 | grep -q "Lab1/src/main/java/lab1/Division.java"; then
              mvn -Dtest=lab1.DivisionTest test
            elif git diff --name-only HEAD~1 | grep -q "Lab1/src/main/java/lab1/Caffeine.java"; then
              mvn -Dtest=lab1.CaffeineTest test
            elif git diff --name-only HEAD~1 | grep -q "Lab1/src/main/java/lab1/Mortgage.java"; then
              mvn -Dtest=lab1.MortgageTest test
            elif git diff --name-only HEAD~1 | grep -q "Lab1/src/main/java/lab1/NumSquared.java"; then
              mvn -Dtest=lab1.NumSquaredTest test
            elif git diff --name-only HEAD~1 | grep -q "Lab1/src/main/java/lab1/OutputWithVars.java"; then
              mvn -Dtest=lab1.OutputWithVarsTest test
            elif git diff --name-only HEAD~1 | grep -q "Lab1/src/main/java/lab1/Parking.java"; then
              mvn -Dtest=lab1.ParkingTest test
            elif git diff --name-only HEAD~1 | grep -q "Lab1/src/main/java/lab1/BasicOutput.java"; then
              mvn -Dtest=lab1.BasicOutputTest test
            else
              echo "No relevant files were changed. Skipping tests."
            fi
          fi
