name: Autograding All Code

on:
  push:
    paths:
      # Lab 1 files
      - "Lab1/src/main/java/lab1/Division.java"
      - "Lab1/src/test/java/lab1/DivisionTest.java"
      - "Lab1/src/main/java/lab1/Caffeine.java"
      - "Lab1/src/test/java/lab1/CaffeineTest.java"
      - "Lab1/src/main/java/lab1/Mortgage.java"
      - "Lab1/src/test/java/lab1/MortgageTest.java"
      - "Lab1/src/main/java/lab1/NumSquared.java"
      - "Lab1/src/test/java/lab1/NumSquaredTest.java"
      - "Lab1/src/main/java/lab1/OutputWithVars.java"
      - "Lab1/src/test/java/lab1/OutputWithVarsTest.java"
      - "Lab1/src/main/java/lab1/Parking.java"
      - "Lab1/src/test/java/lab1/ParkingTest.java"
      - "Lab1/src/main/java/lab1/BasicOutput.java"
      - "Lab1/src/test/java/lab1/BasicOutputTest.java"

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ./Lab1  # Ensure the right path for the project

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Build with Maven
        run: mvn clean compile

      - name: Run tests
        run: mvn test

