name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Compile and run tests
        run: |
          # Check if there is a previous commit
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            MODIFIED_MODULES=$(git diff --name-only HEAD~1 | grep '^Lab' | cut -d '/' -f 1 | sort -u)
          else
            # Handle the case where there is no previous commit
            MODIFIED_MODULES=$(ls -d Lab*/)
          fi

          echo "Modified modules: $MODIFIED_MODULES"

          if [ -z "$MODIFIED_MODULES" ]; then
            echo "No relevant modules modified."
          else
            for module in $MODIFIED_MODULES; do
              echo "Running tests for $module"
              mvn clean test -pl $module -am
            done
          fi
